#source 'http://rubygems.org'
source 'http://ruby.taobao.org/'

gem 'rails', '4.0.0'
gem 'mysql2', '~> 0.3.11'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 2.3.2.0'
gem 'haml-rails'
gem 'faye'
gem 'devise', '~> 3.2.3'
gem 'sqlite3'
gem 'coffee-rails', '~> 4.0.0'
